name: Docker Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and run Docker containers
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Test Docker containers
      run: |
        docker-compose up -d
        docker ps -a
        docker logs chat-server